export const VH_Variables = {
    active_account_token: '',
    isCTActive: false,
    virtual_account_token: '',
    isVHActive: false,
    allow_VH: false,
    account_switched: false,
    allow_switch: false,
    is_authorized: false,
    active_index: 0,
    results: [],
    user_tokens: [],
    blocky_cp: false,
    max_steps: 0,
    current_step: 1,
    min_trades_real: 0,
    current_trades_real: 0,
    allow_martingale: false,
    martingale_factor: 1,
    isMartingaleActive: false,
    mart_total_lost: 0,
    mart_stake: 0.35,
    take_profit: 1000000,
    stop_loss: 1000000,
    global_blocky: null,
};
